name: Docker Image Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:

      - name: Upwind Security ShiftLeft Scan
        uses: upwindsecurity/shiftleft-create-image-scan-event-action@main
        with:
          upwind_client_id: ${{ secrets.UPWIND_CLIENT_ID }}
          upwind_client_secret: ${{ secrets.UPWIND_CLIENT_SECRET }}
          docker_image: '693339160499.dkr.ecr.us-east-1.amazonaws.com/cgr.dev/upwind.io/adoptium-jdk-fips:latest'
          pull_image: true
          upwind_uri: upwind.dev
